import { Router } from 'express';
import { healthRoutes } from './healthRoutes.js';
import { createRoomRoutes } from './roomRoutes.js';
import { createQuizRoutes } from './quizRoutes.js';
import { QuizController } from '../controllers/quizController.js';
import { RoomController } from '../controllers/roomController.js';
import { PrismaQuizRepository } from '../repositories/quizRepository.js';
import { PrismaRoomRepository } from '../repositories/roomRepository.js';
import { QuizService } from '../services/quizService.js';
import { RoomService } from '../services/roomService.js';
import { prisma } from '../lib/prisma.js';
import { InMemoryGameRepository } from '../repositories/gameRepository.js';
import { GameService } from '../services/gameService.js';
import { GameController } from '../controllers/gameController.js';
import { createGameRoutes } from './gameRoutes.js';
import { AuthService } from '../auth/authService.js';
import { createAuthRoutes } from './authRoutes.js';
import { loadConfig } from '../config/env.js';
import { requireAuth } from '../auth/middleware.js';
import { PrismaGameReportRepository } from '../repositories/reportRepository.js';
import { GameReportService } from '../services/reportService.js';
import { ReportController } from '../controllers/reportController.js';
import { createReportRoutes } from './reportRoutes.js';

export const routes = Router();
const config = loadConfig();
export const authService = new AuthService(prisma, { clientId: config.googleClientId, clientSecret: config.googleClientSecret, callbackUrl: config.googleCallbackUrl, frontendOrigin: config.frontendUrl, allowedOrigins: config.frontendOrigins, secureCookies: config.secureCookies, sessionSecret: config.sessionSecret, resendApiKey: config.resendApiKey, emailFrom: config.emailFrom, googleAuthMode: config.googleAuthMode, nodeEnv: config.nodeEnv });
routes.use(createAuthRoutes(authService));
routes.use(healthRoutes);
const quizRepository = new PrismaQuizRepository(prisma);
const roomRepository = new PrismaRoomRepository(prisma);
export const quizService = new QuizService(quizRepository);
export const roomService = new RoomService(roomRepository, quizService);
const gameRepository = new InMemoryGameRepository();
const reportService = new GameReportService(new PrismaGameReportRepository(prisma), gameRepository, roomService, quizService);
export const gameService = new GameService(gameRepository, roomService, quizService, { onFinished: (game) => reportService.capture(game) });
routes.use(createQuizRoutes(new QuizController(quizService), requireAuth));
routes.use(createRoomRoutes(new RoomController(roomService, quizService)));
routes.use(createGameRoutes(new GameController(gameService)));
routes.use(createReportRoutes(new ReportController(reportService), requireAuth));
