export type DomainErrorCode =
  | 'INVALID_QUIZ'
  | 'QUIZ_NOT_FOUND'
  | 'QUIZ_ID_CONFLICT'
  | 'QUIZ_STORE_ERROR'
  | 'QUIZ_IN_USE'
  | 'QUIZ_HAS_HISTORY'
  | 'GAME_NOT_FOUND'
  | 'GAME_ALREADY_IN_PROGRESS'
  | 'GAME_ALREADY_FINISHED'
  | 'GAME_ID_CONFLICT'
  | 'GAME_STORE_ERROR'
  | 'ROOM_NOT_STARTABLE'
  | 'QUIZ_NOT_STARTABLE'
  | 'GAME_NOT_IN_PROGRESS'
  | 'QUESTION_NOT_STARTED'
  | 'QUESTION_NOT_ACTIVE'
  | 'QUESTION_ALREADY_ACTIVE'
  | 'QUESTION_NOT_EXPIRED'
  | 'QUESTION_STATE_CHANGED'
  | 'INVALID_ANSWER'
  | 'QUESTION_NOT_CURRENT'
  | 'QUESTION_NOT_REVEALED'
  | 'QUESTION_NOT_FOUND'
  | 'OPTION_NOT_FOUND'
  | 'QUESTION_EXPIRED'
  | 'ANSWER_ALREADY_SUBMITTED'
  | 'INVALID_QUIZ_ID'
  | 'INVALID_ROOM_PIN'
  | 'ROOM_NOT_FOUND'
  | 'INVALID_PLAYER_NAME'
  | 'PLAYER_ALREADY_EXISTS'
  | 'PLAYER_NOT_FOUND'
  | 'ROOM_NOT_JOINABLE'
  | 'INVALID_ROOM_TRANSITION'
  | 'ROOM_PIN_CONFLICT'
  | 'ROOM_ID_CONFLICT'
  | 'ROOM_STORE_ERROR'
  | 'FORBIDDEN'
  | 'INVALID_CREDENTIALS'
  | 'EMAIL_ALREADY_REGISTERED'
  | 'GOOGLE_OAUTH_NOT_CONFIGURED'

export class DomainError extends Error {
  constructor(
    public readonly code: DomainErrorCode,
    public readonly statusCode: number,
    message: string,
  ) {
    super(message);
    this.name = 'DomainError';
  }
}
